### ISSUE TITLE
Cannot render tiles with React16, Leafletjs 1.3.3 and React-Leaflet 2.0

### ISSUE THREAD

**Issue by cre8te** [mhasbie/react-leaflet-vectorgrid#1]
Hi,
  I cannot get this to render the vector tiles under React16, Leafletjs 1.3.3 and React-Leaflet 2.0 as context is not passed to the child object (it is just undefined).

Line 117
```
var _context = this.context,
map = _context.map,
pane = _context.pane,
layerContainer = _context.layerContainer;
```
I am working on a solution but any assistance would be appreciated.

**Comment by egemon** [comment]
Same to me. Lemme know if u find the solution, I will try as well at mean time

**Comment by egemon** [comment]
@cre8te https://react-leaflet.js.org/docs/en/context.html

**Comment by mhasbie** [comment]
Latest release is published and tested. Works with react@16.5.2, leaflet@1.3.4, and react-leaflet@2.0.1

Closing this now.
