### ISSUE TITLE
Can't use VectorGrid inside LayersControl in v2?

### ISSUE THREAD

**Issue by jordotech** [mhasbie/react-leaflet-vectorgrid#12]
Hello, thanks for this great project.

I'm getting `Cannot read property 'undefined' of undefined` when I try to include my vectorgrid inside of `<LayersControl.Overlay>...`, works fine outside of LayersControl

```
{
    "@material-ui/styles": "4.9.6",
    "leaflet": "1.6.0",
    "react": "16.13.1",
    "react-dom": "16.12.0",
    "react-leaflet": "2.6.3",
    "react-leaflet-vectorgrid": "2.2.1",
    "react-scripts": "3.0.1"
  }
```

Here is a sandbox demonstration:

https://codesandbox.io/s/react-leaflet-vectorgrid-in-layerscontrol-broken-vuips

**Comment by mecmartini** [comment]
I had the same issue, It seems a bug with `react-leaflet` _v2_ on `VectorGrid.js` related to:

```
zIndex: zIndex || Number(layerContainer._panes[pane] && layerContainer._panes[pane].style.zIndex),
				getFeatureId: feature => this._getFeatureId(feature),
```

That's because, on `react-leaflet` _v2_, `layerContainer._panes` isn't set.

To avoid it, make sure to set a `zIndex` _> 0_ on your `VectorGrid` options, like:

```
const options = {
    type: 'protobuf',
    url: 'https://free-{s}.tilehosting.com/data/v3/{z}/{x}/{y}.pbf.pict?key={key}'
    vectorTileLayerStyles: { ... },
    subdomains: 'abcd',
    key: 'abcdefghi01234567890',
    zIndex: 1,
};
```

It worked for me.

**Comment by jordotech** [comment]
That fixed it!  Thank you so much, working version https://codesandbox.io/s/react-leaflet-vectorgrid-in-layerscontrol-fixed-pj7jx
