### ISSUE TITLE
`key` is a special React property

### ISSUE THREAD

**Issue by trevorgerhardt** [mhasbie/react-leaflet-vectorgrid#5]
I understand the intention of using `key` but since it is a special react property it throws an Error: https://reactjs.org/warnings/special-props.html

Would a pull request be welcome that changes the prop name to `accessKey`? We may want to change `token` to `accessToken` for naming consistency also.

**Comment by mhasbie** [comment]
Thanks @trevorgerhardt for pointing that out. Your suggestions is well received and is now incorporated in v2.2.0

P/s: You are always welcome to open a PR. Thanks.
