### ISSUE TITLE
`find` is undefined

### ISSUE THREAD

**Issue by trevorgerhardt** [mhasbie/react-leaflet-vectorgrid#6]
Is the intention to use a self written `find` function or the JavaScript `Array#find`? https://github.com/mhasbie/react-leaflet-vectorgrid/blob/master/src/VectorGrid.js#L306

Can open a PR with a fix for this also.

**Comment by mhasbie** [comment]
This issue is fixed in v2.2.0. Thanks for reporting.

P/s: Again, you are always welcome to open a PR. Thanks. ;)
