### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by deanban** [mhasbie/react-leaflet-vectorgrid#7]
<img width="1209" alt="screen shot 2018-12-04 at 1 08 56 pm" src="https://user-images.githubusercontent.com/3989225/49463177-ce815300-f7c5-11e8-979d-bed67a2efd43.png">

I'm importing a geojson file into react app. Here's my dependencies-

`"dependencies": {
    "axios": "^0.18.0",
    "leaflet": "^1.3.4",
    "lodash": "^4.17.11",
    "react": "^16.6.3",
    "react-dom": "^16.6.3",
    "react-leaflet": "^2.1.2",
    "react-leaflet-vectorgrid": "^2.1.3",
    "react-redux": "^5.1.1",
    "react-scripts": "2.1.1",
    "redux": "^4.0.1",
    "redux-thunk": "^2.3.0"
  },`
Is it because something wrong with the data? When I tried with a small snippet of the data on jsfiddle example it works.

**Comment by Mispulin** [comment]
Same problem here.

**Comment by mhasbie** [comment]
@deanban, @Mispulin  do you mind sharing the jsfiddle that replicate this issue? Thanks.

**Comment by Mispulin** [comment]
@mhasbie I actually stopped having this problem moments later but I was so in a zone of working that I lost track of what fixed it.

**Comment by mhasbie** [comment]
I shall close this issue then. Feel free to reopen if you encounter them again.

**Comment by giridharkl** [comment]
I am still getting the similar error. Please help. I am using react-leaflet:2.21; react: 16.8.3.

`import React, { Component } from 'react';
import { Map, TileLayer, Marker, Popup, LayersControl } from 'react-leaflet';
import "leaflet/dist/leaflet.css";
import icon from 'leaflet/dist/images/marker-icon.png';
import iconShadow from 'leaflet/dist/images/marker-shadow.png';
import { ReactLeafletSearch } from 'react-leaflet-search';
//import {GeoSearchControl, OpenStreetMapProvider} from 'leaflet-geosearch';

import L from 'leaflet';

delete L.Icon.Default.prototype._getIconUrl;

/* L.Icon.Default.mergeOptions({
    iconRetinaUrl: require('leaflet/dist/images/marker-icon-2x.png'),
    iconUrl: require('leaflet/dist/images/marker-icon.png'),
    shadowUrl: require('leaflet/dist/images/marker-shadow.png')
}); */



class MapLeaflet extends Component {

    state = {
        lat: 60.192059, 
        lng: 24.945831,
        zoom: 13,
    };

    myIcon = L.icon({
        iconUrl: 'marker-icon.png',
        iconRetinaUrl: 'marker-icon-2x.png',
        shadowUrl: 'marker-shadow.png',
        iconSize: [25, 41],
        iconAnchor: [12, 41],
        popupAnchor: [1, -34],
        tooltipAnchor: [16, -28],
        shadowSize: [41, 41]
    });

    customPopup(SearchInfo) {
        return(
          <Popup>
            <div>
              <p>I am a custom popUp</p>
              <p>latitude and longitude from search component: {SearchInfo.latLng.toString().replace(',',' , ')}</p>
              <p>Info from search component: {SearchInfo.info}</p>
              <p>{SearchInfo.raw && SearchInfo.raw.place_id && JSON.stringify(SearchInfo.raw.place_id)}</p>
            </div>
          </Popup>
        );
      }

    render() {
        const position = [this.state.lat, this.state.lng];

        const SearchComponent = props => (
            console.log(this.props),
            <ReactLeafletSearch
                      position="topleft"
                      provider="OpenStreetMap"
                      providerOptions={{region: 'gb'}} />
          );
        //const wrappedZoomIndicator = withLeaflet(ReactLeafletZoomIndicator);
        return (
            <Map center={position} zoom={this.state.zoom} style={{
                marginLeft: this.props.expanded ? 240 : 64,
                padding: this.props.expanded?'15px 35px 0px 20px':'15px 35px 0px 20px',
                position: 'absolute',
                height: '97%',
                width: this.props.expanded?'77%':'90%',
                bounds: this.state.bounds,
                maxBounds: this.state.maxBounds
            }}>
                <LayersControl position="topright">
                    <LayersControl.BaseLayer name="OpenStreetMap.BlackAndWhite">
                        <TileLayer
                        attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
                        url="https://tiles.wmflabs.org/bw-mapnik/{z}/{x}/{y}.png"
                        />
                    </LayersControl.BaseLayer>
                    <LayersControl.BaseLayer name="OpenStreetMap.Color">
                        <TileLayer
                        attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
                        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
                        />
                    </LayersControl.BaseLayer>
                    <TileLayer
                        attribution='&amp;copy <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
                        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
                    />
                </LayersControl>
                
                <Marker position={position}>
                    <Popup>
                        <span>A pretty CSS3 popup. <br /> Easily customizable.</span>
                    </Popup>
                </Marker>
                <SearchComponent />
            </Map>
        );
    };

}

export default MapLeaflet;`

**Comment by ZaninAndrea** [comment]
I solved this by following the instructions [here](https://github.com/mhasbie/react-leaflet-vectorgrid#usage-with-react-leaflet-v2), this applies if you are using react-leaflet v2.

@giridharkl you may try this
