### ISSUE TITLE
Having trouble using the component in typescript

### ISSUE THREAD

**Issue by ZakRabe** [mhasbie/react-leaflet-vectorgrid#8]
Im developing integration in our app using storybook. Im doing this in order to test usage and performance. 

but I get this error in storybook

`Failed to execute 'postMessage' on 'Worker': Symbol(react.element) could not be cloned.`

I think we need the v2 syntax since we use the later versions of the react leaflet. I believe we've got the deps correct

package.json versions

```
"lodash": "4.17.11",
"react": "16.8.3",
"react-leaflet": "2.2.0",
"react-leaflet-vectorgrid": "2.2.1",
```

i've created a simple definition file for the library 
definition file

`src\types\react-leaflet-vectorgrid.d.ts`

```
declare module 'react-leaflet-vectorgrid' {
  import VectorGrid = require('react-leaflet-vectorgrid');
  export = VectorGrid;
}
```

 I just created a simple interface and component wrapper from the docs

```import * as React from 'react';
import { withLeaflet } from 'react-leaflet';
import VectorGridDefault from 'react-leaflet-vectorgrid';

const VectorGridComponent: any = withLeaflet(VectorGridDefault);

export interface VectorGridProps {
  data: Object;
  type?: 'slicer' | 'protobuf';
  idField?: string;
  tooltip?: string;
  popup?: Function;
  style?: Object;
  hoverStyle?: Object;
  activeStyle?: Object;
  zIndex?: number;
  interactive?: boolean;
  onClick?: Function;
  onMouseover?: Function;
  onMouseout?: Function;
  onDblclick?: Function;
}

class VectorGrid extends React.Component<VectorGridProps, {}> {
  render() {
    return <VectorGridComponent {...this.props} />;
  }
}

export default VectorGrid;
```

but i get the error at the top of the post. I've inspected the value of VectorGridComponent , and it seems to be off. Am I missing something or not using the correct syntax perhaps? any advice would be immensely helpful

thanks

I've tried the v1 syntax of just importing and using as a component, but I get:
`Cannot read property 'map' of undefined`

**Comment by jayarjo** [comment]
@ZakRabe did you found a solution?
