### ISSUE TITLE
Component not updating/re-rendering on changing redux props

### ISSUE THREAD

**Issue by apal21** [mhasbie/react-leaflet-vectorgrid#9]
I'm using this library to load a GeoJSON file but I'm changing the opacity using redux. For the first time, it is loading the proper opacity but not updating it after dispatching the actions to update props.

Currently, to make this thing work, I added this code but it is a bit laggy.
```javascript
updateLeafletElement(oldProps, newProps) {
    if (oldProps != newProps) {
        this.forceUpdate();
    }
}
```

I think there should be a way to make this work properly.

**Comment by mecmartini** [comment]
You must set a unique key value on your vector layer. This is not documented on `react-leaflet-vectorgrid` but it is on `react-leaflet.`

As example, in my case I managed it like this:

```javascript
const provinceKey = 'province_' + regionFilter + provinceFilter + departmentFilter;
const departmentkey = 'department_' + regionFilter + provinceFilter + departmentFilter;

...

return(
  <VectorGrid key={provinceKey} {...provincesOptions} />
  <VectorGrid key={departmentkey} {...departementsOptions} />
)
```

**Comment by apal21** [comment]
Thank you for the response. 
I'll try this and let you know in this thread.

**Comment by apal21** [comment]
Thank you @mecmartini. It is working properly. Closing this issue.
